[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
extra_scripts =
  pre:scripts/generate_bms_config_header.py
build_unflags =
  -std=gnu++11
build_flags =
  -std=gnu++17
  -DBMS_USE_AFE_MONITOR=0
